"""Initial migration.

Revision ID: ed612dff67e1
Revises: 
Create Date: 2024-12-20 13:19:01.053740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed612dff67e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('test',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('complete_time', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('user_inputs', sa.Text(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('webLink', sa.Text(), nullable=True),
    sa.Column('tgLink', sa.Text(), nullable=True),
    sa.Column('auth_token', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=False),
    sa.Column('test_type', sa.String(length=36), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('answers', sa.Text(), nullable=True),
    sa.Column('current_question_id', sa.String(length=36), nullable=True),
    sa.Column('next_question_id', sa.String(length=36), nullable=True),
    sa.Column('time_spent', sa.Interval(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_inputs', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('session')
    op.drop_table('question')
    op.drop_table('test')
    op.drop_table('user')
    # ### end Alembic commands ###
